### ISSUE TITLE
NameError: name 'w' is not defined

### ISSUE THREAD

**Issue by posetr** [ebubekirunlu/eArsiv-Fatura-App#1]
merhaba ,

**earsiv.py", line 32, in <module>
    w.get('https://earsivportal.efatura.gov.tr/intragiris.html')
    ^
NameError: name 'w' is not defined**

yukarıdaki şekilde bir hata almaktayım.

**Comment by ebubekirunlu** [comment]
w = webdriver.Chrome("chromedriver.exe")

dizininizde chromedriver.exe olduğundan emin olun.

**Comment by posetr** [comment]
hızlı dönüş için teşekkür ederim. örnek bir faturalar.csv dosyası iletir misiniz.

**Comment by ebubekirunlu** [comment]
> hızlı dönüş için teşekkür ederim. örnek bir faturalar.csv dosyası iletir misiniz.

repoya da ekledim... 
[faturalar.csv](https://github.com/ebubekirunlu/eArsiv-Fatura-App/files/12717878/faturalar.csv)
[faturalar.xlsx](https://github.com/ebubekirunlu/eArsiv-Fatura-App/files/12717879/faturalar.xlsx)

**Comment by posetr** [comment]
Aynı faturaya birden fazla hizmet ekleyebilir miyiz?

**Comment by ebubekirunlu** [comment]
Şu hali ile mümkün değil, yeni bir güncelleme ile yapılabilir.. 
yapılacaklar listesine eklendi.

**Comment by posetr** [comment]
Fatura oluşturduktan sonra , Tamam butonuna basamadığı için ikinci faturayı oluşturmuyor.

**Comment by ebubekirunlu** [comment]
> Fatura oluşturduktan sonra , Tamam butonuna basamadığı için ikinci faturayı oluşturmuyor.

Deneme yapılabilsin diye yorum satırına çevrilmişti.

#w.find_element_by_css_selector("div[rel='olustur'] input").click()

Yorum satırından satırından # kaldırın butona basacaktır.

**Comment by posetr** [comment]
Onu kaldırdım fakat ondan sonra bir bir popup daha geliyor oraya tamam demeden  ikinci faturaya geçmiyor.

**Comment by posetr** [comment]
Çoklu ürün ekleme ve tamam butonu ile ilgili güncellemeler ne zaman gelir ?

**Comment by posetr** [comment]
en alt satıra : w.find_element_by_tag_name('body').send_keys(Keys.ESCAPE)

ekleyerek tamam sorununu çözdüm. Diğer işlem için güncellemeyi yaparsanız mutlu olurum.

**Comment by ebubekirunlu** [comment]
> en alt satıra : w.find_element_by_tag_name('body').send_keys(Keys.ESCAPE)
> 
> ekleyerek tamam sorununu çözdüm. Diğer işlem için güncellemeyi yaparsanız mutlu olurum.

Boş zamanlarımda firmamız için geliştirme yapıyorum, tek ürünlü faturalar kestiğimiz için birden fazla ürün için düşünmemiştim hiç...  müsait bir zaman bulduğumda eklemeleri yapmaya çalışacağım... 

Repo'yu fork'layıp geliştirilmesine katkıda bulunabilirsiniz...
